---
title: "Analysis and Diagnostics of Koram macaques"
author: "Jonathan Reeves"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, echo=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(rethinking)
library(knitr)

koram <- read.csv("../Data/koram.csv")
```

# Model Specification


```{r model spec}

model_spec <-   alist(
    U ~ dbinom(1, p),
    logit(p) <- a[H] + h[H] * bC * C,
    a[H] ~ dnorm(0,1.5),
    h[H] ~ dnorm(0,1.5),
    bC ~ dlnorm(0,.3)
  )

```

# Application of model to the social learning condition

## Diagnostic Run with 1 Chain

```{r koram single change run, echo=FALSE}

set.seed(11) # seed is set for reproducibility


nodes <- koram

dat <- list(
  U = nodes$U,
  C = nodes$EV_C,
  A = nodes$A,
  H = nodes$H
)

koram_single_chain <- ulam(
  model_spec,
  data = dat, 
  chains = 1,
  cores = 1,
  iter = 2000,
  log_lik = TRUE, 
  cmdstan = TRUE
  )


```

No errors or warnings returned.

## Run again for diagnostics

The model is re-run using 3 chains to ensure that the posterior distributions is 
appropriately sampled.


```{r Koram 3 chain run, echo=FALSE}

set.seed(11) # seed is set for reproducibility

dat <- list(
  U = nodes$U,
  C = nodes$EV_C,
  A = nodes$A,
  H = nodes$H
)

koram.m <- ulam(
  model_spec,
  data = dat, 
  chains = 3,
  cores = 3,
  iter = 2000,
  log_lik = TRUE, 
  cmdstan = TRUE
  )


```

### Summary of outcome

```{r Koram summary sample}

row_names <- c("Intercept: Common-Like, not-tool-using age",
               "Intercept: Hybrid-Like, not-tool-using age",
               "Intercept: Common-Like, tool-using age",
               "Intercept: Hybrid-Like, tool-using age",
               "Hair Pattern: Common-Like, not-tool-using age", 
               "Hair Pattern: Hybrid-Like, not-tool-using age",
               "Hair Pattern: Common-Like, tool-using age",
               "Hair Pattern: Hybrid-Like, tool-using age",
               "Centrality")
        
koram_model_sum <- precis(koram.m,depth = 2)
koram_model_link <- apply(koram_model_sum, 2, inv_logit)
koram_model_link <- round(koram_model_link,3)
koram_model_link[,5] <- round(koram_model_sum$n_eff)
rownames(koram_model_link) <- row_names

write.csv(koram_model_link,"koram_ABM_Marginal_Distributions_2.csv")
```

### Markov Chain Performance

#### Trace Plot

```{r Koram trace plot}

traceplot(koram.m, pars = c("a[1]",
                            "a[2]",
                            "a[3]",
                            "a[4]",
                            "h[1]",
                            "h[2]",
                            "h[3]",
                            "h[4]",
                            "bC"))
```

#### Trank Plot

```{r Koram trank plot}

trankplot(koram.m, pars = c("a[1]",
                            "a[2]",
                            "a[3]",
                            "a[4]",
                            "h[1]",
                            "h[2]",
                            "h[3]",
                            "h[4]",
                            "bC"))
```



